import { Github, Code, Activity, BarChart2, Info } from 'lucide-react';
import Navbar from '../components/Navbar';
import HousingPredictor from '../components/HousingPredictor';

const HousingProjectPage = ({ onBack }) => <div className="min-h-screen bg-paper text-ink">
    <Navbar title="California Housing — ML Case Study" showBackButton onBackClick={onBack}/>
    <div className="pt-24 px-5 sm:px-6 pb-16"><div className="max-w-6xl mx-auto space-y-8">
        <div className="bg-surface rounded-lg p-5 sm:p-8 border border-line"><div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6"><div className="flex-1"><h1 className="font-display text-3xl sm:text-4xl font-semibold text-ink mb-4 leading-tight">California Housing Price Prediction</h1><p className="text-ink-2 text-lg mb-6">Étude de régression XGBoost avec feature engineering géographique, validation croisée et analyse du compromis entre nombre de variables et performance.</p><div className="flex flex-wrap gap-2">{['Python','XGBoost','Feature Engineering','GeoPandas','Scikit-learn','Cross-validation'].map(tag=><span key={tag} className="font-mono bg-raised text-muted px-2 py-1 rounded text-sm border border-line-soft">{tag}</span>)}</div></div><a href="https://github.com/juleescourne/california-housing-price-prediction" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 bg-surface border border-line hover:border-accent hover:text-accent text-ink-2 px-4 py-2.5 rounded-md font-medium transition"><Github size={18}/>Code source</a></div></div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[['0,8338','R² holdout exploratoire'],['0,8317','R² CV moyen'],['≈ 40 273 $','RMSE'],['15','Variables retenues']].map(([v,l])=><div key={l} className="bg-surface rounded-lg p-4 sm:p-6 border border-line"><div className="font-mono tabular text-xl sm:text-3xl font-semibold text-ink mb-2">{v}</div><div className="text-sm text-muted">{l}</div></div>)}</div>
        <div className="bg-accent-soft border border-line rounded-lg p-5 flex gap-3"><Info className="text-accent flex-shrink-0"/><p className="text-ink-2 text-sm">La démo navigateur ci-dessous affiche un <strong>score relatif 0–100</strong> pour comparer les zones dans un scénario donné. Ce score n’est pas une estimation monétaire calibrée. Le dépôt documente les vraies métriques du modèle et les limites de validation.</p></div>
        <div className="bg-surface rounded-lg p-5 sm:p-8 border border-line"><h2 className="font-display text-2xl font-semibold text-ink mb-3 leading-tight">Démo de scénarios</h2><p className="text-muted mb-6">Ajustez les caractéristiques du quartier pour comparer le score relatif produit par le modèle selon la localisation.</p><HousingPredictor/></div>
        <div className="bg-surface rounded-lg p-5 sm:p-8 border border-line"><h2 className="font-display text-2xl font-semibold text-ink mb-8 text-center leading-tight">Méthodologie & résultats</h2><div className="grid md:grid-cols-3 gap-8">{[
            [Activity,'Méthodologie',['EDA & nettoyage','Feature engineering géographique','Sélection exploratoire de variables','Validation croisée']],
            [Code,'Technologies',['XGBoost','Pandas / NumPy','Scikit-learn','GeoPandas / Matplotlib']],
            [BarChart2,'Lecture prudente',['R² holdout : 0,8338','R² CV : 0,8317','RMSE ≈ 40 273 $','Holdout utilisé pendant l’exploration : limite documentée']]
        ].map(([Icon,title,items])=><div key={title} className="text-center"><div className="bg-accent-soft w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"><Icon/></div><h3 className="font-display text-lg font-semibold text-accent mb-3 leading-tight">{title}</h3><ul className="space-y-2 text-ink-2 text-sm">{items.map(i=><li key={i}>{i}</li>)}</ul></div>)}</div></div>
    </div></div>
</div>;
export default HousingProjectPage;
