import { Github, Code, Activity, BarChart2, Info } from 'lucide-react';
import Navbar from '../components/Navbar';
import HousingPredictor from '../components/HousingPredictor';

const HousingProjectPage = ({ onBack }) => <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
    <Navbar title="California Housing — ML Case Study" showBackButton onBackClick={onBack}/>
    <div className="pt-24 px-6 pb-12"><div className="max-w-7xl mx-auto space-y-8">
        <div className="bg-slate-800/50 rounded-xl p-8 border border-slate-700"><div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6"><div className="flex-1"><h1 className="text-4xl md:text-5xl font-bold text-white mb-4">California Housing Price Prediction</h1><p className="text-gray-300 text-lg mb-6">Étude de régression XGBoost avec feature engineering géographique, validation croisée et analyse du compromis entre nombre de variables et performance.</p><div className="flex flex-wrap gap-2">{['Python','XGBoost','Feature Engineering','GeoPandas','Scikit-learn','Cross-validation'].map(tag=><span key={tag} className="bg-purple-600/20 text-purple-300 px-3 py-1 rounded-lg text-sm border border-purple-500/30">{tag}</span>)}</div></div><a href="https://github.com/juleescourne/california-housing-price-prediction" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 bg-slate-700 hover:bg-slate-600 text-white px-4 py-2 rounded-lg transition"><Github size={18}/>Code source</a></div></div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[['0,8338','R² holdout exploratoire'],['0,8317','R² CV moyen'],['≈ 40 273 $','RMSE'],['15','Variables retenues']].map(([v,l])=><div key={l} className="bg-slate-800/50 rounded-xl p-6 border border-slate-700"><div className="text-2xl md:text-3xl font-bold text-purple-300 mb-2">{v}</div><div className="text-sm text-gray-400">{l}</div></div>)}</div>
        <div className="bg-amber-950/30 border border-amber-500/30 rounded-xl p-5 flex gap-3"><Info className="text-amber-300 flex-shrink-0"/><p className="text-amber-100/90 text-sm">La démo navigateur ci-dessous affiche un <strong>score relatif 0–100</strong> pour comparer les zones dans un scénario donné. Ce score n’est pas une estimation monétaire calibrée. Le dépôt documente les vraies métriques du modèle et les limites de validation.</p></div>
        <div className="bg-slate-800/50 rounded-xl p-8 border border-slate-700"><h2 className="text-2xl font-bold text-white mb-3">Démo de scénarios</h2><p className="text-gray-400 mb-6">Ajustez les caractéristiques du quartier pour comparer le score relatif produit par le modèle selon la localisation.</p><HousingPredictor/></div>
        <div className="bg-slate-800/50 rounded-xl p-8 border border-slate-700"><h2 className="text-2xl font-bold text-white mb-8 text-center">Méthodologie & résultats</h2><div className="grid md:grid-cols-3 gap-8">{[
            [Activity,'Méthodologie',['EDA & nettoyage','Feature engineering géographique','Sélection exploratoire de variables','Validation croisée']],
            [Code,'Technologies',['XGBoost','Pandas / NumPy','Scikit-learn','GeoPandas / Matplotlib']],
            [BarChart2,'Lecture prudente',['R² holdout : 0,8338','R² CV : 0,8317','RMSE ≈ 40 273 $','Holdout utilisé pendant l’exploration : limite documentée']]
        ].map(([Icon,title,items])=><div key={title} className="text-center"><div className="bg-purple-600/20 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"><Icon/></div><h3 className="text-lg font-bold text-purple-400 mb-3">{title}</h3><ul className="space-y-2 text-gray-300 text-sm">{items.map(i=><li key={i}>{i}</li>)}</ul></div>)}</div></div>
    </div></div>
</div>;
export default HousingProjectPage;
