import { useMemo, useState } from 'react';
import Plot from 'react-plotly.js';
import demo from '../data/goodreads-demo.json';
const fmt = n => n.toLocaleString('fr-FR');
const baseLayout = { font: {family:'IBM Plex Sans, sans-serif',size:14,color:'#3b4644'},paper_bgcolor:'#fff',plot_bgcolor:'#fff',margin:{l:55,r:20,t:20,b:60},autosize:true };
const config = { responsive:true,displaylogo:false,modeBarButtonsToRemove:['select2d','lasso2d'] };
export default function GoodreadsExplorer(){
 const [genre,setGenre]=useState(''),[language,setLanguage]=useState(''),[minimum,setMinimum]=useState(100),[weight,setWeight]=useState(1000);
 const prior=useMemo(()=>demo.books.reduce((s,b)=>s+b.rating,0)/demo.books.length,[]);
 const books=useMemo(()=>demo.books.filter(b=>(!genre||b.genre===genre)&&(!language||b.language===language)&&b.votes>=minimum),[genre,language,minimum]);
 const ranked=[...books].map(b=>({...b,score:(b.votes*b.rating+weight*prior)/(b.votes+weight)})).sort((a,b)=>b.score-a.score||b.votes-a.votes);
 const popularity=[...books].sort((a,b)=>b.votes-a.votes),total=books.reduce((s,b)=>s+b.votes,0),share=total?popularity.slice(0,10).reduce((s,b)=>s+b.votes,0)/total*100:0;
 let cumulative=0;const curve=popularity.map(b=>total?(cumulative+=b.votes)/total*100:0);
 return <section className="bg-surface border border-line rounded-lg p-5 sm:p-8 space-y-6">
  <div><p className="font-mono text-sm text-accent mb-2">Laboratoire interactif · données synthétiques</p><h2 className="font-display text-3xl font-semibold text-ink mb-3">Popularité, appréciation et solidité du signal</h2><p className="text-ink-2">Une équipe éditoriale doit choisir quels titres tester en découverte. Comparez la note brute à une note régularisée, puis observez la concentration de l’attention. Les résultats ci-dessous illustrent la méthode, pas le marché du livre.</p></div>
  <details className="bg-paper border border-line rounded p-4"><summary className="cursor-pointer font-medium">Traçabilité et contrôles de qualité</summary><p className="mt-3">{fmt(demo.quality.input)} lignes générées → {fmt(demo.quality.output)} titres conservés : {demo.quality.duplicates} doublon, {demo.quality.invalidRating} note hors 0–5 et {demo.quality.invalidDate} date invalide écartés. {demo.quality.unknownLanguage} langue inconnue et {demo.quality.missingPages} nombre de pages manquant conservés et signalés.</p><p className="text-sm text-muted mt-2">Graine 42 ; noms fictifs ; volume de notes asymétrique simulé. Ce contrôle pédagogique rejette les notes invalides : il est distinct du pipeline Python historique, qui les borne. Les graphiques Power BI plus bas proviennent d’un autre jeu de données.</p><a className="text-accent underline" href="https://github.com/juleescourne/goodreads-analytics-etl/blob/main/scripts/build_demo_data.py">Consulter le générateur et ses règles</a></details>
  <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
   <label>Genre<select className="demo-input" value={genre} onChange={e=>setGenre(e.target.value)}><option value="">Tous</option>{[...new Set(demo.books.map(b=>b.genre))].sort().map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Langue<select className="demo-input" value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Toutes</option>{[...new Set(demo.books.map(b=>b.language))].sort().map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Minimum de notes<select className="demo-input" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}>{[0,100,1000,10000].map(v=><option key={v} value={v}>{fmt(v)}</option>)}</select></label>
   <label>Poids de régularisation m<select className="demo-input" value={weight} onChange={e=>setWeight(Number(e.target.value))}>{[100,1000,10000].map(v=><option key={v} value={v}>{fmt(v)}</option>)}</select></label>
  </div>
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4" aria-live="polite">{[[fmt(books.length),'titres filtrés'],[fmt(total),'notes cumulées'],[share.toFixed(1)+' %','des notes sur les 10 premiers titres']].map(([v,l])=><div key={l} className="p-4 bg-paper rounded"><strong className="font-mono text-2xl block">{v}</strong><span className="text-sm text-muted">{l}</span></div>)}</div>
  {!books.length?<p role="status">Aucun titre ne satisfait ces critères. Diminuez le minimum de notes ou élargissez les filtres.</p>:<div className="grid lg:grid-cols-2 gap-6">
   <div className="min-w-0"><h3 className="font-display text-xl font-semibold">Une bonne note n’implique pas une forte visibilité</h3><Plot data={[{type:'scatter',mode:'markers',x:books.filter(b=>b.votes>0).map(b=>b.votes),y:books.filter(b=>b.votes>0).map(b=>b.rating),text:books.filter(b=>b.votes>0).map(b=>`${b.title}<br>${fmt(b.votes)} notes · ${b.rating}/5`),hovertemplate:'%{text}<extra></extra>',marker:{color:'#0d5e63',size:8,opacity:.5}}]} layout={{...baseLayout,xaxis:{type:'log',title:{text:'Nombre de notes · échelle logarithmique'}},yaxis:{range:[0,5],title:{text:'Note moyenne / 5'}}}} config={config} useResizeHandler style={{width:'100%',height:340}}/><p className="text-sm text-muted">Chaque point est un titre. Les titres sans notes sont exclus du graphique logarithmique ({books.filter(b=>!b.votes).length} ici). Les avis ne sont ni des ventes ni des lecteurs uniques.</p></div>
   <div className="min-w-0"><h3 className="font-display text-xl font-semibold">Où se concentre l’attention ?</h3><Plot data={[{type:'scatter',mode:'lines',x:[0,...curve.map((_,i)=>(i+1)/curve.length*100)],y:[0,...curve],fill:'tozeroy',line:{color:'#0d5e63'},name:'Titres triés par popularité',hovertemplate:'%{x:.1f} % des titres → %{y:.1f} % des notes<extra></extra>'},{type:'scatter',mode:'lines',x:[0,100],y:[0,100],line:{color:'#626d6a',dash:'dot'},name:'Répartition égale'}]} layout={{...baseLayout,xaxis:{title:{text:'Part des titres, du plus au moins noté (%)'}},yaxis:{range:[0,100],title:{text:'Part cumulée des notes (%)'}},showlegend:false}} config={config} useResizeHandler style={{width:'100%',height:340}}/><p className="text-sm text-muted">La diagonale représente une attention répartie également. La courbe est recalculée sur le périmètre filtré ; elle n’établit pas une loi de puissance.</p></div>
  </div>}
  <h3 className="font-display text-2xl font-semibold">Candidats à examiner · classement régularisé</h3><p className="text-sm text-muted">Score = (n × note + m × C) / (n + m), avec C = {prior.toFixed(2)}, moyenne des titres du jeu complet. m est un choix de sensibilité, pas un seuil validé. Ce score réduit l’influence des petits volumes ; il ne constitue pas un intervalle de confiance.</p>
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Titre fictif','Note brute','Nombre de notes','Score régularisé'].map(h=><th key={h} className="text-left p-3 border-b border-line">{h}</th>)}</tr></thead><tbody>{ranked.slice(0,10).map(b=><tr key={b.id}><td className="p-3 border-b border-line">{b.title}</td><td>{b.rating.toFixed(2)}</td><td>{fmt(b.votes)}</td><td className="font-mono">{b.score.toFixed(2)}</td></tr>)}</tbody></table></div>
  <div className="bg-accent-soft p-4 rounded"><strong>Passer de l’observation à une décision</strong><p>Retenir des candidats suffisamment documentés, puis tester leur mise en avant avec un groupe témoin. Mesurer le taux de clic, l’ajout à une liste et la diversité des titres exposés. Sans impressions, historique temporel et expérimentation, aucun gain de conversion ou de revenu n’est démontré.</p></div>
 </section>;
}
